API implentación soporte Xavi Denise
PTIN2022/A2 pull request #11
Opened 2022-04-23 14:20 UTC by denisenavarro

2022-04-23 20:23 UTC, xaviermazon submitted a review, later dismissed
Pro mi parte todo correcto, adelante el PR

2022-04-24 13:27 UTC, Sergi030 commented on cloud-service-api/models/soporte.py
> +class Soporte(db.Model):
Faltara una clase mensaje, para meter los mensajes en una tabla aparte

2022-05-03 16:20 UTC, ShadowFurtive commented on cloud-service-api/models/soporte.py
> +class Soporte(db.Model):
He añadido la clase, pero no sirve de mucho ya que falta añadir cosas en la documentación respecto a esto: 
- Obtener los mensajes de un ticket
- Obtener los mensajes escritos por un usuario
Una vez hecho esto, se debe implementar en el alchemy. Que los que hayan hecho soporte lo hagan cuanto antes por que esto se escribió hace 10 días xd.

2022-05-08 18:35 UTC, denisenavarro commented on cloud-service-api/models/soporte.py
> +class Soporte(db.Model):
Se ha modificado la docu y se ha añadido la clase chat

2022-05-10 07:39 UTC, xaviermazon approved these changes, later dismissed

2022-05-12 21:07 UTC, ShadowFurtive requested changes
Por ahora lo veo bien, pero antes de hacer la PR se deben arreglar los errores con el main (hay varios archivos que pueden dar problemas, haz un merge localmente y mira a ver si se arregla, si no lo haremos este finde).

2022-05-13 21:39 UTC, ShadowFurtive submitted a review, later dismissed

2022-05-14 07:56 UTC, xaviermazon approved these changes, later dismissed

2022-05-14 10:20 UTC, Sergi030 commented on API/api-gestion.yml
>    /soporte/ticket_id/{user_id}:
porque ponemos aqui ticket_id?

2022-05-14 11:53 UTC, Sergi030 commented on API/api-gestion.yml
>                    value: |-
cambiar esto por lo que usamos siempre

2022-05-14 11:54 UTC, Sergi030 commented on API/api-gestion.yml
>                        "descripcion": "Problema con la aplicación móvil"
añadir la coma para que se formate bien

2022-05-14 11:54 UTC, Sergi030 commented on API/api-gestion.yml
> -                        "fecha": "01/02/20222",
Tendría sentido guardar también la hora?

2022-05-14 11:55 UTC, Sergi030 commented on cloud-service-api/models/chat.py
> +    msg_id = db.Column(db.Integer, nullable=False, primary_key=True)
funciona bien si el autoincrement?

2022-05-14 11:56 UTC, Sergi030 commented on cloud-service-api/models/soporte.py
> +        # self.user_id = user_id
entiendo que en un futuro esto si estara?

2022-05-14 11:58 UTC, Sergi030 requested changes
he puesto un par de comments

2022-05-14 12:09 UTC, ShadowFurtive commented on cloud-service-api/models/soporte.py
> +        # self.user_id = user_id
Esto si

2022-05-14 12:09 UTC, ShadowFurtive commented on cloud-service-api/models/chat.py
> +    msg_id = db.Column(db.Integer, nullable=False, primary_key=True)
si

2022-05-14 12:09 UTC, ShadowFurtive commented on API/api-gestion.yml
> -                        "fecha": "01/02/20222",
Lo cambio

2022-05-15 11:29 UTC, Sergi030 commented on cloud-service-api/models/chat.py
> +    fecha = db.Column(db.String(15), nullable=False)
Lo guardamos como string en vez de datetime ? o date?

2022-05-15 11:31 UTC, Sergi030 commented on cloud-service-api/models/chat.py
> +    fecha = db.Column(db.String(15), nullable=False)
Y vuelvo a preguntar, queremos guardar minutos ? (en mi mente tendría sentido)

2022-05-15 11:31 UTC, Sergi030 commented on cloud-service-api/models/soporte.py
> +    fecha = db.Column(db.String(15), nullable=False)
Lo guardamos como string en vez de datetime ? o date? 

guardar minutos too ?

2022-05-15 11:32 UTC, Sergi030 commented on API/api-gestion.yml
> -                        "fecha": "01/02/20222",
aun falta meter horas y mins :D

2022-05-15 12:04 UTC, Sergi030 commented on cloud-service-api/routes/soporte.py
> +        return jsonify({"error": "Ticket not found."}), 404
en la doc tienes "Ticket no encontrado."

2022-05-15 12:05 UTC, Sergi030 commented on API/api-gestion.yml
> +        '400':
en el get este 400 no tiene sentido

2022-05-15 12:06 UTC, Sergi030 commented on API/api-gestion.yml
> +                      "chat": [ {
estos chat, en la implementacion es "Mensajes"

2022-05-15 12:07 UTC, Sergi030 commented on API/api-gestion.yml
> +                Insertar petición a soporte tecnico:
Cambiar, texto estás consultando, no insertando

2022-05-15 12:08 UTC, Sergi030 commented on API/api-gestion.yml
> +      summary: Dado un usuario en concreto pueda generar una petición para un ticket
cambiar esto para que se entienda mejor, este post es para contestar a un ticket

2022-05-15 12:09 UTC, Sergi030 commented on cloud-service-api/routes/soporte.py
> +        fecha = datetime.strptime(fecha, '%Y-%m-%d %H:%M')
No se si tiene sentido que desde la web pasen la fecha en vez de pillar la fecha actual directamente

2022-05-15 12:12 UTC, Sergi030 commented on cloud-service-api/controller/soporteController.py
> +    s = Chat(ticket_id, mensaje, fecha)
quizas el ticket_id no existe

2022-05-15 12:13 UTC, Sergi030 commented on cloud-service-api/routes/soporte.py
> +        control.post_soporte_by_ticket(ticket_id, mensaje, fecha)
si el ticket id no existe devolveras un null, deberias en el controler comprobar esto, y aquí devolver el ticket not found si el ticket no existe

2022-05-16 07:14 UTC, Sergi030 commented on cloud-service-api/models/chat.py
> +    mensaje = db.Column(db.Integer, nullable=False)
String(500), comunicarse por números no debe ser bueno :P

2022-05-16 15:27 UTC, Sergi030 approved these changes

2022-05-16 16:42 UTC, merged