3/05/2022 guillem api estaciones app
PTIN2022/A2 pull request #13
Opened 2022-05-03 11:47 UTC by WilliamBoy

2022-05-04 19:29 UTC, xaviermazon commented
2 Cosas:
- Los Yaml deberian estar en un solo yml?
- He ejecutado el make test de edge-service-api y ha salido esto:
FAILED tests/test_incidencias.py::test_get_all_incidencias_empty - assert 404 == 200
FAILED tests/test_incidencias.py::test_post_incidencia - assert 404 == 400
FAILED tests/test_incidencias.py::test_get_all_incidencias_one - assert 404 == 200
FAILED tests/test_incidencias.py::test_post_2_incidencias - assert 404 == 200
FAILED tests/test_incidencias.py::test_get_incidencia_by_name - assert 404 == 200
FAILED tests/test_incidencias.py::test_get_incidencias_by_id - assert 404 == 200
FAILED tests/test_incidencias.py::test_remove_incidencia - AssertionError: assert None == {'error': 'Incidencia not found.'}
FAILED tests/test_incidencias.py::test_modify_incidencia - AssertionError: assert None == {'error': 'Incidencia not found.'}

2022-05-04 19:55 UTC, xaviermazon approved these changes

2022-05-12 21:08 UTC, ShadowFurtive commented on API/estacions_app.yaml
> +openapi: 3.0.0
Esto va a la api-app

2022-05-12 21:08 UTC, ShadowFurtive commented on API/estacions_app.yaml
> +  /estaciones/disponible:
Esta respecto a la /estaciones/areas/<areas> en que se diferencia?

2022-05-12 21:11 UTC, ShadowFurtive commented on API/estacions_app.yaml
> +  /estaciones/Area/{idArea}:
Esta no la veo la utilidad, en plan, creo que los de la app cogerán y enseñaran todas las estaciones disponibles al usuario, no van a ir por areas. Esto sería buena idea si fuese para un mapa interactivo como google maps que va cargando elementos a medida que va moviendose por el mapa

2022-05-12 21:11 UTC, ShadowFurtive commented on API/estacions_app.yaml
> +  /estaciones/disponible:
Lo mismo que arriba, al menos que lo hayas hecho para el mapa tampoco lo veo util (que no se si tendran un mapa los de la app)

2022-05-12 21:11 UTC, ShadowFurtive commented on API/estacions_app.yaml
> +  /estaciones/Disponible/Area/{idArea}:
Esto es lo mismo que el de arriba no?

2022-05-12 21:13 UTC, ShadowFurtive commented on API/estacions_app.yaml
> +  /estaciones/byreserva/{idreserva}:
Este no lo veo necesario tampoco

2022-05-12 21:13 UTC, ShadowFurtive commented on edge-service-api/controller/reservasController.py
> +def get_reservas_estacion(estacion):
Esto está anticuado

2022-05-12 21:14 UTC, ShadowFurtive commented on edge-service-api/routes/reservas.py
> +        desde = request.json["desde"]
Esto también está anticuado

2022-05-12 21:16 UTC, ShadowFurtive requested changes
En general no veo que esté bien, yo creo que lo suyo sería centrarse en sacar simplemente estaciones y ya, si quieres sacar una cantidad de estaciones por cercania lo suyo seria hacerlo por coordenadas, por otro lado, este PR si se acepta va a reventar el main por que tiene cosas antiguas que el github reconoce como nuevas, por ende, lo que está bien en el main se verá borrado por el PR. Igualmente no te ralles que esto ya nos encargamos los de la API en este sprint.

2022-05-13 21:40 UTC, closed without merging