2022 05 03 - sgarcia dockers deployment
PTIN2022/A2 pull request #14
Opened 2022-05-03 18:18 UTC by Sergi030

2022-05-03 18:30 UTC, raulgamero approved these changes

2022-05-03 20:50 UTC, ShadowFurtive requested changes

2022-05-03 20:50 UTC, ShadowFurtive commented on API/api-gestion.yml
> +  - url: craaxkvm.epsevg.upc.es:23601/api
Has probado que funcione adequadamente? he probado de hacer un get con el swagger editor y puede ser que suceda que al compartir el mismo puerto con el de la página web, no funcione adecuadamente (me sale que ha habido un error de network) y en el api tester no response.

2022-05-04 11:26 UTC, Sergi030 commented on API/api-gestion.yml
> +  - url: craaxkvm.epsevg.upc.es:23601/api
Lo del craax no lo probé directamente ahí, si no que probé en local con los dockers como si fuera el craax, y lo que hace el nginx justamente es eso se pone a usar el puerto 23601 y si va a /api va al docker de api y el resto al front

2022-05-04 11:28 UTC, Sergi030 commented on nginx/nginx.conf
> +    proxy_pass        http://api:5000;
@ShadowFurtive Aquí es donde de hace lo del redirigir la api

2022-05-04 11:29 UTC, Sergi030 commented on API/api-gestion.yml
> +  - url: craaxkvm.epsevg.upc.es:23601/api
Y claro aún no funciona porque hasta no merger esto no lo subiré al cloud

2022-05-04 11:44 UTC, ShadowFurtive commented on API/api-gestion.yml
> +  - url: craaxkvm.epsevg.upc.es:23601/api
Okey, le doy como approved

2022-05-04 11:45 UTC, ShadowFurtive approved these changes

2022-05-04 16:03 UTC, merged