2022-04-12 api-gestion.yml estaciones y arreglo incidencias
PTIN2022/A2 pull request #2
Opened 2022-04-12 11:24 UTC by peroivi

Hemos actualizado la api de gestion, la parte de Estaciones y hemos arreglado los POST de incidencias.

2022-04-12 11:32 UTC, Sergi030 commented on API/api-gestion.yml
>                    value: "{\"error\": \"User not authenticated.\"}"
porque no usas el formato? >- 
                                                {json}

2022-04-12 11:34 UTC, Sergi030 requested changes
Cambiar formato errores al mismo de las content value

2022-04-18 12:00 UTC, Sergi030 approved these changes

2022-04-18 12:00 UTC, ShadowFurtive approved these changes

2022-04-18 12:01 UTC, merged