docu-api-promociones
PTIN2022/A2 pull request #21
Opened 2022-05-14 23:00 UTC by raulgamero

Señores aquí os tiro la docu de promociones.
Cosas a decir:
- Al hacer el POST de promoción obligo a meter el id_estacion. Os mola eso o preferis que metan el nombre de la estación?
- La otra cosa es que comentamos el tema de hacer GET por fechas. He visto en el UML que hay un atributo que se llama 'estado'. He entendido que se refiere a si la promoción esta inactiva o activa, y he pensado que con eso se podría hacer. Os mola con eso o ponga lo de las fechas? Igual no he pensado en que ese atributo quizás sea difícil de mantener...
Ya me decís!

2022-05-15 09:54 UTC, ShadowFurtive requested changes
Añadiria unas cuantas cosas:
- /promociones/estacion/{estacion_id}/{estado}
- /promociones/estacion/{estacion_id/{fecha_ini}/{fecha_fin}


Está si te ve con ganas, pero no se si va a llegar a utilitzar (les tengo que preguntar).
- /promociones/estacion/{estacion_id/{fecha_ini}/{fecha_fin}/{estado}

Para cambiar: 
Cuando haces un get de las promociones (/promociones, /promociones/{estado}. /promociones/{id}) deberías incluir a que estácion pertenecen. En la implementación esto es fácil, solo debes incluir en el meta un fk_include = True. 

La de /promociones/{estado} está bien pensada. 
Lo de la estación le pasamos por ahora un **Integer** (1,2,3) ya que es como está estipulado en los modelos, así que está perf

2022-05-15 11:40 UTC, ShadowFurtive commented on API/api-gestion.yml
> +                        "estacion": 2,
Los id estaciones aqui deberian ser iguales

2022-05-15 11:41 UTC, ShadowFurtive commented on API/api-gestion.yml
> +                        "estacion": 3,
Id estacion igual a las otras ya que haces /promociones/{estaciones}

2022-05-15 11:41 UTC, ShadowFurtive commented on API/api-gestion.yml
> +                        "estacion": 3,
estacion id diferentes

2022-05-15 11:41 UTC, ShadowFurtive commented on API/api-gestion.yml
> +                        "estacion": 3,
id_estacion

2022-05-15 11:42 UTC, ShadowFurtive commented on API/api-gestion.yml
> +                        "descuento": 20,
id_estaciones diferentes aqui

2022-05-15 11:42 UTC, ShadowFurtive commented on API/api-gestion.yml
> +                        "cantidad_usados": "8",
id_estaciones_diferentes

2022-05-15 11:43 UTC, ShadowFurtive commented on API/api-gestion.yml
> +                        "cantidad_usados": "8",
Cambia esos valores y ya se puede hacer merge :)

2022-05-15 11:45 UTC, Sergi030 commented on API/api-gestion.yml
> +                          "cantidad_usados": "10",
preguntales a los de la web si esto sigue siendo asi, porque diria que han dicho de aplicar descuentos directamente entre 2 fechas, sin meter cupones ni nada

2022-05-15 11:46 UTC, Sergi030 commented on API/api-gestion.yml
> +                          "fecha_fin": "22-10-2022",
Yo entiendo que tendría sentido tener también hora, minuto inicio, ejemplo: quizás quieres aplicar promos desde las 12:00PM hasta las 5:00AM porque por la noche no carga nadie

2022-05-15 11:46 UTC, Sergi030 requested changes
pregunta lo de los cupones y mirate lo de añadir hora y minutos

2022-05-15 11:48 UTC, Sergi030 commented
> * a cosa es que comentamos el tema de hacer GET por fechas. He visto en el UML que hay un atributo que se llama 'estado'. He entendido que se refiere a si la promoción esta inactiva o activa, y he pensado q

Yo veo bien lo de los id, y lo del estado lo mantendría junto a las fechas, porque puedes tener creada la promoción pero no activarla

2022-05-15 12:13 UTC, raulgamero commented on API/api-gestion.yml
> +                        "cantidad_usados": "8",
srry se me ha olvidado revisar los numeros

2022-05-15 12:14 UTC, raulgamero commented on API/api-gestion.yml
> +                          "fecha_fin": "22-10-2022",
okey les digo

2022-05-15 12:22 UTC, raulgamero commented on API/api-gestion.yml
> +                          "cantidad_usados": "10",
lo puse porq estaba en el UML, he habalado con marc y hemos quedado en que quitamos lo de cupones y dejamos el descuento entre fechas

2022-05-15 12:23 UTC, raulgamero commented on API/api-gestion.yml
> +                          "fecha_fin": "22-10-2022",
Me comentan que estaria bien hacerlo pero solo si no nos va a complicar mucho. Creeis que sera dificillo de implementar o le damos caña?

2022-05-15 19:28 UTC, xaviermazon commented
Vale, entonces por mi parte que hago en la de mobil me espero a que acabeis? asi hago un copypaste?

2022-05-19 17:16 UTC, raulgamero commented
He cambiado lo de promociones y ahora esta sin relacion a estaciones. Me lo ha pedido el Alfredo que lo pongamos en produccion aunque no este relacionado para que lo pueda ir trabajando. Ya cuando arreglemos los models lo cambiare.

2022-05-19 17:17 UTC, raulgamero commented
Tambien he quitado lo de los cupones que hablamos, ya que no tenian mucho sentido si habia fecha de caducidad

2022-05-20 21:05 UTC, ShadowFurtive submitted a review, later dismissed

2022-05-20 21:09 UTC, ShadowFurtive approved these changes

2022-05-21 09:40 UTC, merged