2022 5 14 xavier app promociones
PTIN2022/A2 pull request #29
Opened 2022-05-20 08:15 UTC by xaviermazon

2022-05-20 22:04 UTC, ShadowFurtive commented on edge-service-api/controller/promocionesController.py
> +        for cargador in i.id_promo:
Esto que es?

2022-05-20 22:05 UTC, ShadowFurtive commented on edge-service-api/controller/promocionesController.py
> +    print(str(id))
Este print?

2022-05-20 22:07 UTC, ShadowFurtive commented on API/api-app.yml
> +  /promociones/{id_promocion}:
Faltan:
- GET /promociones -> Te devuelve todas las promociones activas.
Ademas de eso, deberias haber metido algun filtro o algo para saber cuales son las promociones activas. 
Puede haber promociones que su estado sea False y nos sirve de nada enseñarlas. 
Puede haber promociones que su fecha de caducidad ha pasado y tampoco sirve para enseñarlas. 
Esto no se ve reflejado en ningun sitio

2022-05-20 22:15 UTC, ShadowFurtive requested changes
Entiendo que si has puesto el review-me es por que esto según crees está acabado, si no te lo comento para que lo tengas en cuenta para cuando te vuelvas a poner a implementar:
Aparte de los fallos que te he mencionado, se nota bastante que es un ctrl+c ctrl+v medio pocho, ni se han puesto bien los nombres de las funciones.  
Aparte de eso, ni has probado a ver si funcionaban las funciones de forma correcta. Ni has mirado si el modelo estaba bien declarado como en la web, que es de cual tenias que básicamente copiar y adaptarlo para la app. 
En el modelo, los cupones sobran (lo puedes ver en la api de promociones de la web, que raul lo comenta). 
Para probar si funcionaba solo tenias que añadir esto en la app.py y verias que solo funciona la de obtenerlo por el id...
....
    p = Promocion(20, datetime.strptime("2022/04/20 18:00", "%Y/%m/%d %H:%M"), datetime.strptime("2022/04/20 19:00", "%Y/%m/%d %H:%M"), True, "asdas")
    db.session.add(p)
    db.session.commit()
    pe = PromocionEstacion(e.id_estacion,p.id_promo )
    db.session.add(pe)
    db.session.commit()
....
Y bueno, aparte de los comentarios que te he puesto, echale una ojeada nueva al código y curratelo un poco más por que esto lo tiene que usar los de la app y no podemos hacer un merge de algo que no funciona.

2022-05-21 10:18 UTC, xaviermazon commented
Yo pregunte en su momento si me tenia que espera que a la API de cloud de las promociones estuviese terminada o no y lo que se me dijo es que no iba diferente, ahora me pongo en ello

2022-05-21 17:50 UTC, xaviermazon commented
Esta solo que cree un test para promociones y mirar el promociones estaciones

2022-06-16 08:27 UTC, merged