Arreglos API promociones
PTIN2022/A2 pull request #39
Opened 2022-06-16 20:56 UTC by raulgamero

Funciona todo bien pero queria comentar unas cosas antes de hacer merge y que me digais:
- Boolean para el estado de la promocion en vez de string?
- He puesto un application/json en vez de un multiplatform, lo pongo como antes para no cambiarles mucho o lo dejo en application/json?

2022-06-17 08:40 UTC, Sergi030 commented on API/api-gestion.yml
>                    Meter trabajador:
Cambia esto a algo con sentido pls

2022-06-17 08:43 UTC, Sergi030 commented on cloud-service-api/controller/promocionesController.py
> +    i = Estacion.query.filter(Estacion.id_estacion == id_estacion).one_or_none()
Esto de pillar la estacion deberias hacerlo antes de crear la promo, entonces comprobar si estacion None, devolver un json de error y si encuentras estación, hacer lo de la promo.

Ahora crearias promos y después petaría por que la estacion no existe

2022-06-17 08:44 UTC, Sergi030 commented on cloud-service-api/controller/promocionesController.py
>              p.descripcion = descripcion
entiendo que falta el caso de modificar el cantidad usados

2022-06-17 08:45 UTC, Sergi030 commented on cloud-service-api/routes/promociones.py
> +        descripcion = request.json["descripcion"]
Entiendo que falta el caso de modificar el cantidad usados

2022-06-17 16:23 UTC, raulgamero commented on API/api-gestion.yml
>                    Meter trabajador:
donee srry

2022-06-17 16:25 UTC, raulgamero commented on cloud-service-api/controller/promocionesController.py
> +    i = Estacion.query.filter(Estacion.id_estacion == id_estacion).one_or_none()
donee tambien

2022-06-17 16:25 UTC, raulgamero commented on cloud-service-api/controller/promocionesController.py
>              p.descripcion = descripcion
en el post no hace falta se pone a zero automaticamente

2022-06-17 16:25 UTC, raulgamero commented on cloud-service-api/routes/promociones.py
> +        descripcion = request.json["descripcion"]
aqui si lo he añadido

2022-06-17 16:31 UTC, raulgamero commented
Lo del estado de momento lo he dejado en string.
Lo de la cantidad usados lo puesto para que se modificar desde el PUT, aun asi creo que donde habria que ir actualizando su valor es cuando realmente se use la promocion (a la hora de pagar y tal..)
Hay algunas cosas que cuelgan un poco aún asi:
 - A la hora de hacer el POST solo se puede indicar una estación, ya que se supone que recibe un id_estacion solo. ¿Lo cambio para que sea un string del palo (1-2-3) i asi se pueda introducir más de una estación o lo dejo así?
 - Cuando se hace el PUT realmente no se elimina la estación a la que este asociada la promo si no que se añade la que se ponga en el json. Ejemplo: Si la promocion con id = 1 esta asociada a la estacion 1 y haces el put y pones el id_estacion=2 la promo se quedara asociada a las estacion con id=1 y id=2. ¿Que hacemos con esto? si se quiere eliminar alguna habría que pedir cual se quiere eliminar supongo
Merci chicos, ya me decís

2022-06-18 10:15 UTC, Sergi030 commented
> 

Yo esto que comentas del post, creo que seria interesante que nos pasen una lista de strings y despues vayas añadiendo en todas las estaciones.

lo del put, yo entiendo que es normal que se vayan añadiendo y me parece guay, lo que quizás necesitamos un método para eliminar una promo de una estación rollo DELETE /promo/{id_promo}/{id_estacion}

y un delete global que sea /promo/{id_promo} que borra toda la promocion en si

2022-06-18 17:00 UTC, ShadowFurtive reviewed
Perdon por la tardanza, primero:
el estado no sé si se deberia dejar en booleano. Creo que los estados son activo o no activo, así que un booleano estaria bien. Si no un string y que añaden lo que quieran. 
Lo ded application/json, dejalo como estaba y no te compliques con eso.

En hacer lo del post, estaria interesante que pasen un string con el id de estaciones. Pq una promo está pa varias estaciones.

El put está bien planteado. Se deberia crear los delete pertinentes como menciona Sergi. 
Bien exo raul :)

2022-06-18 17:03 UTC, ShadowFurtive commented on cloud-service-api/controller/promocionesController.py
> +        return EstacionSchema(many=True).dump(a)
Esto quizás es mas interesante que devuelva promocion con un json de las estaciones. En plan { <info promo>... , "Estacion" : [ { <info estacion> }, { <info estacion> }, { <info estacion> }, { <info estacion> }] }

2022-06-18 17:03 UTC, ShadowFurtive approved these changes
Este PR debe esperar a lo del token

2022-06-19 10:06 UTC, Sergi030 commented on cloud-service-api/routes/promociones.py
> +        descripcion = request.json["cantidad_usados"]
Cuidado, has puesto descripcion

2022-06-19 10:12 UTC, raulgamero commented on cloud-service-api/routes/promociones.py
> +        descripcion = request.json["cantidad_usados"]
yes, sorry

2022-06-23 12:01 UTC, ShadowFurtive commented on API/api-gestion.yml
> +                          "estado": "activa",
Solo una activa por promo

2022-06-23 12:05 UTC, ShadowFurtive requested changes
faltan los tokens_required en routes, si no los añades se va hacer un lio en el main. Puedes ver que hay conflictos y es por esto mismo. En este caso, es fácil añádirlo, solo  debes añadir en cada funcion lo siguiente:
@token_required
funcion name(current_trabajador)
if current_trabajador==administrador or current_trabajador==encargado
...
else
return user not authorized

El resto de cosas las mirare a fondo cuando añadas esto. Intenta añadirlo hoy. 
Si tienes alguna duda hablame.

2022-06-25 05:47 UTC, Sergi030 commented on cloud-service-api/controller/promocionesController.py
> +def modify_estado(id_promo, id_estacion):
Aquí hay otro dilema, que las promociones son dadas una fecha inicio y una fecha final, que pasara si tienes una promo activa para hoy y mañana tienes otra, ahora mismo si la última es la de hoy, la de mañana estará inactiva, pero realmente al mismo tiempo si las 2 estuvieran activas, no se solaparían, es esto lo que se quiere?

2022-06-25 11:38 UTC, ShadowFurtive commented on cloud-service-api/controller/promocionesController.py
> +def modify_estado(id_promo, id_estacion):
Esto habrá que hacer una funcion o algun servicio que estuviese al tanto de esto, seria el responsable de desactivar la promo en caso que haya pasado la fecha.

2022-06-25 18:14 UTC, closed without merging