Denise xavier soporte
PTIN2022/A2 pull request #4
Opened 2022-04-14 15:41 UTC by xaviermazon

@Sergi030 y @ShadowFurtive cuando os sea posible haced una revision

2022-04-15 11:18 UTC, Sergi030 requested changes
Lo suyo sería tenerlo todo en el mismo fichero de api-gestión.yml

Porque así toda la api estará en un mismo sitio y abra solo 1 web y no 5.


Podrias juntarlo todo pls

2022-04-15 11:20 UTC, Sergi030 commented
También has subido 2 ficheros vacíos que no entiendo el de mqtt y el sus, es por algo en especial?

2022-04-15 11:24 UTC, xaviermazon commented
> También has subido 2 ficheros vacíos que no entiendo el de mqtt y el sys, es por algo en especial?
Yo con las ramas soy un novato y a veces no se que me hago con git y magit

2022-04-15 11:32 UTC, xaviermazon reviewed
@Sergi030

2022-04-17 11:02 UTC, Sergi030 commented on API/soporte_tecnico_post.yml
> +openapi: 3.0.0
Faltaría mergear esta con la de api_gestion

2022-04-17 11:03 UTC, Sergi030 commented on soporte_tecnico_post.yml
> +openapi: 3.0.0
Faltaría juntar está con la de api_gestion

2022-04-17 11:03 UTC, Sergi030 requested changes
Faltaría juntar los yml con api-gestion

2022-04-18 12:02 UTC, ShadowFurtive requested changes
Coged el archivo original yml  y juntarlo, teniendo el  yml con el mismo nombre.

2022-04-21 12:26 UTC, Sergi030 commented on API/api-gestion.yml
> +	# Creacion de una ayuda o ticket al soporte tecnico
eliminar tab

2022-04-21 12:26 UTC, Sergi030 commented on API/api-gestion.yml
> + 	# Eliminacion del ticket o peticion al soporte tecnico
eliminar tab

2022-04-21 12:26 UTC, Sergi030 commented on API/api-gestion.yml
> +	delete:
eliminar tab

2022-04-21 12:32 UTC, Sergi030 commented on API/api-gestion.yml
> +                      "id_usuario": "001",
Yo aquí también, metería un ticket_id

2022-04-21 12:33 UTC, Sergi030 commented on API/api-gestion.yml
> +  /soporte/userid:
Entocnes aqui en vez de usar userid usaria ticket id, ya que un usuario puede tener mas de un ticketm y entiendo que este get es para ver el ticket en si


![image](https://user-images.githubusercontent.com/22755318/164458799-49a38a6f-0604-43f5-8d25-be2f4a7614c8.png)

2022-04-21 12:34 UTC, Sergi030 commented on API/api-gestion.yml
> +  /soporte/userid:
y para la parte del delete igual, es mejor eliminar ticket_id que tickets de usuarios

2022-04-21 12:37 UTC, Sergi030 commented on API/api-gestion.yml
> +  /soporte/userid:
y tambien para que la web sea capaz de pasar el  ticket el formato debe ser algo tal que asi:

  /soporte/{id}: # <------ fijaros que el id tiene unos brakets y despues en parameters se dice que este id es un int
      get:
        tags: 
        - Trabajadores
        parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer


Asi el id puede ser un numero y si se va a /soporte/55 iremos al ticket 55

2022-04-21 20:38 UTC, ShadowFurtive commented on API/api-gestion.yml
> +                      "id_usuario": "001",
Faltaria el ticket id y yo creo que ya estaría listo

2022-04-22 12:26 UTC, ShadowFurtive approved these changes, later dismissed

2022-04-22 19:46 UTC, Sergi030 commented
Creo que en algún momento habéis pillado una versión antigua, y habéis sobrescrito cambios que ya estaban, si queréis podemos quedar para ver como arreglarlo

2022-04-22 19:47 UTC, Sergi030 commented on API/api-gestion.yml
> +                  type: string
int

2022-04-22 19:47 UTC, Sergi030 commented on API/api-gestion.yml
> +              type: string
int

2022-04-22 19:48 UTC, Sergi030 commented on API/api-gestion.yml
> +              type: string
int

2022-04-23 08:09 UTC, ShadowFurtive commented on API/api-gestion.yml
> +                  value: "[{\n\t\t\"incidencia_id\": 1,\n\t\t\"estacion\": \"VG1\",\n\t\t\"direccion\": \"Av.Victor Balaguer 2\",\n\t\t\"fecha_averia\": \"18 Mar 2022 \",\n\t\t\"estado\": false,\n\t\
?

2022-04-23 08:10 UTC, ShadowFurtive commented on API/api-gestion.yml
> +                  value: "{\"error\": \"User not authenticated.\"}"
Falla formato error

2022-04-23 08:11 UTC, ShadowFurtive commented on API/api-gestion.yml
> +                id_usuario:
ticket_id en esta linea

2022-04-23 08:11 UTC, ShadowFurtive commented on API/api-gestion.yml
> +              id_usuario: 1
ticket_id aqui

2022-04-23 08:12 UTC, ShadowFurtive commented on API/api-gestion.yml
> +                      "id_usuario": "001",
meter ticket id aqui tmb en el ejemplo

2022-04-23 08:12 UTC, ShadowFurtive commented on API/api-gestion.yml
> +                      "TicketId": 0123456789,
Intentad que coincidan los valores de properties con el value

2022-04-23 17:59 UTC, ShadowFurtive approved these changes

2022-04-24 12:27 UTC, Sergi030 approved these changes

2022-04-24 16:08 UTC, merged