2022 06 19 xmazon app api promociones
PTIN2022/A2 pull request #43
Opened 2022-06-22 10:39 UTC by xaviermazon

Endpoints de API APP Promociones con estaciones.

2022-06-22 14:51 UTC, raulgamero commented on edge-service-api/controller/promocionesController.py
> +        if estado == 'true':
aqui para los de la web sera un string en vez de un bool, pero como esta es para la app supongo que dara igual

2022-06-22 14:58 UTC, raulgamero requested changes

2022-06-22 14:58 UTC, raulgamero commented on edge-service-api/controller/promocionesController.py
> +        if estado == 'true':
por defecto el estado sera 'inactiva'

2022-06-22 14:58 UTC, raulgamero commented on edge-service-api/controller/promocionesController.py
> +def modify_promociones(id_promo, descuento=None, fecha_inicio=None, fecha_fin=None, estado=False, descripcion=None):
aqui dijimos que se podia utilizar tambien para añadir una estacion a la promo. Que te puedan introducir la estacion por parametro y ya tu añadirla a la lista de estaciones de la promo

2022-06-23 11:21 UTC, ShadowFurtive reviewed
Como que hay 45 archivos cambiados? Este PR si lo metemos, veo que nos dará problemas. Deberias crear un PR nuevo con la última versión del main y añadiendo los cambios. Si solo has hecho los EP de promociones solo deberias haber modificado 4 archivos y como mucho 5. Los 4 archivos a modificar: API/api-app.yaml, /control/promocionesController.py,  routes/promociones.py y app.py. Si has tenido que cambiar algo más es en models.py (pero este ultimo es altamente aconsejable que no hayas tocado nada)

2022-06-23 15:56 UTC, Sergi030 commented
> Como que hay 45 archivos cambiados? Este PR si lo metemos, veo que nos dará problemas. Deberias crear un PR nuevo con la última versión del main y añadiendo los cambios. Si solo has hecho los EP de promociones solo deberias haber modificado 4 archivos y como mucho 5. Los 4 archivos a modificar: API/api-app.yaml, /control/promocionesController.py, routes/promociones.py y app.py. Si has tenido que cambiar algo más es en models.py (pero este ultimo es altamente aconsejable que no hayas tocado nada)

Agree con esto, no entiendo lo de 45 ficheros para esto, haz una nueva rama y un nuevo PR pls

2022-06-23 15:56 UTC, closed without merging