Documentación api trabajadores, login y logout
PTIN2022/A2 pull request #7
Opened 2022-04-21 15:22 UTC by raulgamero

2022-04-21 18:00 UTC, Sergi030 commented on API/api-gestion.yml
> +  /trabajadores/{dni}:
trabajadores -> trabajador

2022-04-21 20:35 UTC, ShadowFurtive commented on API/api-gestion.yml
> +                    value: "{\"error\": \"Malformed request syntax.\"}"
Mirad de cambiar este formato de error y de ponerlo de forma génerica al resto del documento.

2022-04-21 20:35 UTC, ShadowFurtive commented on API/api-gestion.yml
> +                    value: "{\"error\": \"Malformed request syntax.\"}"
Se repite varias veces, cambiarlo en todos los sitios

2022-04-21 20:40 UTC, ShadowFurtive commented on API/api-gestion.yml
> +                example:
Falta DNI

2022-04-21 20:40 UTC, ShadowFurtive commented on API/api-gestion.yml
> +              example:
Falta dni en el ejemplo

2022-05-01 10:34 UTC, xaviermazon requested changes

2022-05-01 10:34 UTC, xaviermazon commented on API/api-gestion.yml
> +  /trabajadores/{dni}:
Modificalo

2022-05-01 10:34 UTC, xaviermazon commented on API/api-gestion.yml
> +                example:
Ponselo

2022-05-01 10:34 UTC, xaviermazon commented on API/api-gestion.yml
> +                    value: "{\"error\": \"Malformed request syntax.\"}"
lo quieres asi? value: "{\"error\": \"Sintaxis mal formada.\"}"

2022-05-01 12:20 UTC, Sergi030 commented on API/api-gestion.yml
> +                    value: "{\"error\": \"Malformed request syntax.\"}"
en plan asi: {error: Malformed request syntax.}

sin las comillas

2022-05-03 12:05 UTC, xaviermazon approved these changes
Tanda de errores estan corregidos, buen trabajo!!

2022-05-03 12:05 UTC, xaviermazon commented on API/api-gestion.yml
> +                    value: "{\"error\": \"Malformed request syntax.\"}"
habra que poner esto primero >-

2022-05-03 12:08 UTC, ShadowFurtive approved these changes

2022-05-07 15:12 UTC, closed without merging