ONGOING - 2022 04 18 sgarcia cloud api incidencias
PTIN2022/A2 pull request #9
Opened 2022-04-22 19:14 UTC by Sergi030

2022-04-25 08:11 UTC, raulgamero submitted a review, later dismissed

2022-04-29 19:27 UTC, ShadowFurtive commented on cloud-service-api/routes/incidencias.py
> +@incidencias.route('/incidencias/byname/<estacion>', methods=["GET"])
Esto de aqui devuelve solo una incidencia en caso que una estación tenga varias

2022-04-29 19:27 UTC, ShadowFurtive approved these changes, later dismissed

2022-04-29 19:28 UTC, ShadowFurtive commented on cloud-service-api/routes/incidencias.py
> +@incidencias.route('/incidencias/byname/<estacion>', methods=["GET"])
Le doy como approved pero se deberia mirar de cambiarlo

2022-04-29 19:58 UTC, xaviermazon commented on cloud-service-api/README.md
> +
Se deberia poner algun comentario para instalar flask-sqlalchmy y marshmallow-sqlalchemy

2022-04-29 23:35 UTC, Sergi030 commented on cloud-service-api/README.md
> +
Eso es justo lo que hace el make env, te instala en el virtualenv todas las dependencias

2022-04-30 01:31 UTC, Sergi030 commented on cloud-service-api/routes/incidencias.py
> +@incidencias.route('/incidencias/byname/<estacion>', methods=["GET"])
Cambiado :D

2022-04-30 01:32 UTC, Sergi030 commented on cloud-service-api/routes/incidencias.py
> +@incidencias.route('/incidencias/byname/<estacion>', methods=["GET"])
Arreglado, bien visto (el rollo de los pull request es justo este :100: )

2022-04-30 08:19 UTC, xaviermazon commented on cloud-service-api/README.md
> +
Pues he querido hacerlo y he tenido que instalarlo a mano

2022-04-30 10:40 UTC, ShadowFurtive approved these changes

2022-04-30 10:41 UTC, ShadowFurtive requested changes
Miraria de que cumpliese con el corrector del python3

2022-04-30 12:27 UTC, ShadowFurtive approved these changes

2022-04-30 14:50 UTC, xaviermazon commented
Por mi parte ya esta correcto

2022-04-30 14:51 UTC, xaviermazon approved these changes

2022-05-01 12:19 UTC, merged